
[[constraint]]
  name = "github.com/decred/dcrd"
  revision = "8fda21512f3f64f164f0ac10565144341fbf98e1"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.4.0"

[[constraint]]
  name = "github.com/miekg/dns"
  version = "1.0.8"

[prune]
  go-tests = true
  unused-packages = true
